### ISSUE TITLE
[Tracking] Known Issues and Ideas

### ISSUE THREAD

**Issue by vifino** [carbonsrv/circd#1]
# Known issues for CIRCd:
- [ ] Sometimes, timing out takes a long while.
  - Quit message is like this: read tcp 192.168.1.11:6667->192.168.1.30:11453: read: no route to host
  - Ping out doesn't happen?
- [ ] Basically no features are implemented, and those who are may not follow standards well.
- [ ] No reload of settings
- [ ] No dynamic expansion yet.
  - How about a whitelisted Lua eval? Would simplify debugging a little.
  - Maybe sub layer in the command creation that has command to either call the command or destroy it/replace it? Would allow dynamic reload, too.
# Ideas for the future
- Multi server?
  - Serveral internals have to be rewritten even at this stage. Probably gonna be a fun experience.
